apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mynode-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mynode
    spec:
      containers:
      - name: mynode
        image: prys/mynode
        command: ["node"]
        args: ["/root/node/api.js"]
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
